# Generated by Django 5.1 on 2024-12-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOME')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='N° DE TELEFONE')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('message', models.TextField(max_length=200, verbose_name='MENSAGEM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CRIADO EM')),
                ('response', models.TextField(max_length=200, verbose_name='RESPOSTA')),
                ('r_created_at', models.DateTimeField(verbose_name='RESPOSTA CRIADA EM')),
                ('flag', models.BooleanField(default=False, verbose_name='RESPONDIDO')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ('-created_at',),
            },
        ),
    ]
