# Generated by Django 5.1 on 2024-12-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmodel_r_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='r_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RESPOSTA CRIADA EM'),
        ),
    ]
